name: Java CI

on:
  # See also https://github.community/t5/GitHub-Actions/Selecting-an-Xcode-version/m-p/32340#M1092
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}
    strategy: 
      matrix:
        java: [8, 11] 

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt
      - name: Build with Maven
        run: mvn -B clean install javadoc:javadoc
